### ISSUE TITLE
Nibeuplink test tools shows error

### ISSUE THREAD

**Issue by kusk** [elupus/nibeuplink#4]
I cloned the latest repository and did basic pip3 install . in the repository directory. But when I test the tools using "nibeuplink" I get asked for redirect_url eventhough it was specified as an argument. After that it fails.

**System: Ubuntu 20.04 LTS(up-to-date)**

**Command output:**
```
$ nibeuplink --client_id 9efb......... --client_secret DfGw................................... --redirect_uri "http://master/api/auth"
https://api.nibeuplink.com/oauth/authorize?response_type=code&client_id=9efb....................&redirect_uri=http%3A%2F%2Fmaster%2Fapi%2Fauth&scope=READSYSTEM&state=b222...........................
Enter full redirect url: http://master/api/auth
Traceback (most recent call last):
  File "/home/a/.local/bin/nibeuplink", line 8, in <module>
    sys.exit(main())
  File "/home/a/.local/lib/python3.8/site-packages/nibeuplink/__main__.py", line 186, in main
    loop.run_until_complete(run())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/a/.local/lib/python3.8/site-packages/nibeuplink/__main__.py", line 91, in run
    await session.get_access_token(session.get_code_from_url(result))
  File "/home/a/.local/lib/python3.8/site-packages/nibeuplink/session.py", line 165, in get_code_from_url
    return query["code"][0]
KeyError: 'code'
```

**Comment by elupus** [comment]
The url you give on command line should be the exact value you configured in nibeuplink home page. You will them get redirected to a url in your we browser with that as it's base, but with additional fragments and parameters. That extended url is what you enter when client run.

**Comment by kusk** [comment]
Ah great, now it makes sense and works.
